// This file would normally be generated by Amplify CLI
// For demo purposes, using placeholder values
const awsmobile = {
  aws_project_region: "us-east-1", // HealthScribe is only available in US East (N. Virginia)
  aws_cognito_identity_pool_id: "PLACEHOLDER_IDENTITY_POOL_ID",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "PLACEHOLDER_USER_POOL_ID",
  aws_user_pools_web_client_id: "PLACEHOLDER_USER_POOL_CLIENT_ID",
  aws_user_files_s3_bucket: "PLACEHOLDER_AUDIO_BUCKET_NAME",
  aws_user_files_s3_bucket_region: "us-east-1",
  aws_healthscribe_output_bucket: "PLACEHOLDER_OUTPUT_BUCKET_NAME"
}

export default awsmobile 